### PR TITLE
fix(emitter): remove nanoid

### LINKED ISSUE #45: The error is constantly falling
image

### PR DESCRIPTION
**Pull request by arturovt**
Closes #45

### CODE REVIEW

File: src/lib/core/decorators/receiver.ts [hunk 1]
```diff
@@ -1,7 +1,13 @@
-const generate = require('nanoid/generate');
-
 import { ensureStoreMetadata, ReceiverMetaData, RECEIVER_META_KEY } from '../internal/internals';
 
+/**
+ * @internal
+ * @returns - Generated hash w/o collisions because it's time-based
+ */
+function generate(): string {
```
Comment (splincode) [inline src/lib/core/decorators/receiver.ts]: Rename to `generateHash`

**Comment by splincode** [comment]
Please add

```ts
imports: [
  NgxsEmitPlugin.forRoot({ 
    generator: customGenerateFunction()
  })
]
```

**Comment by arturovt** [comment]
@splincode good
